server:
  port: 8081

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://mysqldb:3306/banking_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    gateway:
      locator:
        discovery: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

